## Credit Risk Scoring With ML

### 1- Loading the data first

In [104]:
#!pip install numpy==1.26.4

#!pip install matplotlib==3.9.2

#!pip install --upgrade matplotlib 



#!pip uninstall matplotlib

#!pip install matplotlib --upgrade

In [105]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import time 
import os

### 2 - Descrebing the dataset to show all its structure

In [106]:
df = pd.read_csv('../data/raw/german_credit_data.csv')

df.head(10)


#data_path = os.path.join("..", "data", "raw", "german_credit_data.csv")

#try:
#    df = pd.read_csv(data_path)
#    print("Dataset found and it is successfully loading !!")
#except FileNotFoundError:
#    print(f"File not found at: {data_path} !!")
#except pd.errors.EmptyDataError:
#    print("The file is entirely empty !!")
#except pd.errors.ParserError:
#    print(f"Parsing error: {e} !!")
    
    
#df.head(10)

,Unnamed: 0,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose,Risk
0,0,67,male,2,own,NaN,little,1169,6,radio/TV,good
1,1,22,female,2,own,little,moderate,5951,48,radio/TV,bad
2,2,49,male,1,own,little,NaN,2096,12,education,good
3,3,45,male,2,free,little,little,7882,42,furniture/equipment,good
4,4,53,male,2,free,little,little,4870,24,car,bad
5,5,35,male,1,free,NaN,NaN,9055,36,education,good
6,6,53,male,2,own,quite rich,NaN,2835,24,furniture/equipment,good
7,7,35,male,3,rent,little,moderate,6948,36,car,good
8,8,61,male,1,own,rich,NaN,3059,12,radio/TV,good
9,9,28,male,3,own,little,moderate,5234,30,car,bad

In [107]:
df = df.drop(columns="Unnamed: 0", axis=1)

df.head(10)

,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose,Risk
0,67,male,2,own,NaN,little,1169,6,radio/TV,good
1,22,female,2,own,little,moderate,5951,48,radio/TV,bad
2,49,male,1,own,little,NaN,2096,12,education,good
3,45,male,2,free,little,little,7882,42,furniture/equipment,good
4,53,male,2,free,little,little,4870,24,car,bad
5,35,male,1,free,NaN,NaN,9055,36,education,good
6,53,male,2,own,quite rich,NaN,2835,24,furniture/equipment,good
7,35,male,3,rent,little,moderate,6948,36,car,good
8,61,male,1,own,rich,NaN,3059,12,radio/TV,good
9,28,male,3,own,little,moderate,5234,30,car,bad

In [108]:
# 1 - show the shape of the dataset

print(f"We have: {df.shape[0]} raws")
print("and")
print(f"We have: {df.shape[1]} columns")

We have: 1000 raws
and
We have: 10 columns

In [110]:
# 2 - describe

df.describe().T

,count,mean,std,min,25%,50%,75%,max
Age,1000.0,35.546,11.375469,19.0,27.0,33.0,42.00,75.0
Job,1000.0,1.904,0.653614,0.0,2.0,2.0,2.00,3.0
Credit amount,1000.0,3271.258,2822.736876,250.0,1365.5,2319.5,3972.25,18424.0
Duration,1000.0,20.903,12.058814,4.0,12.0,18.0,24.00,72.0

In [111]:
# 3 - Show data info

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Age               1000 non-null   int64
 1   Sex               1000 non-null   object
 2   Job               1000 non-null   int64
 3   Housing           1000 non-null   object
 4   Saving accounts   817 non-null    object
 5   Checking account  606 non-null    object
 6   Credit amount     1000 non-null   int64
 7   Duration          1000 non-null   int64
 8   Purpose           1000 non-null   object
 9   Risk              1000 non-null   object
dtypes: int64(4), object(6)
memory usage: 78.2+ KB

In [125]:
print(f"We count 817 values in the [{df.columns[4]}] column, so what it means 183 not valuable values")
print(f"We also count 606 in the [{df.columns[5]}] column, what it means 394 not valuable values")

We count 817 values in the [Saving accounts] column, so what it means 183 not valuable values
We also count 606 in the [Checking account] column, what it means 394 not valuable values

In [79]:
df

,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose,Risk
0,67,male,2,own,NaN,little,1169,6,radio/TV,good
1,22,female,2,own,little,moderate,5951,48,radio/TV,bad
2,49,male,1,own,little,NaN,2096,12,education,good
3,45,male,2,free,little,little,7882,42,furniture/equipment,good
4,53,male,2,free,little,little,4870,24,car,bad
...,...,...,...,...,...,...,...,...,...,...
995,31,female,1,own,little,NaN,1736,12,furniture/equipment,good
996,40,male,3,own,little,little,3857,30,car,good
997,38,male,2,own,little,NaN,804,12,radio/TV,good
998,23,male,2,free,little,little,1845,45,radio/TV,bad
999,27,male,2,own,moderate,moderate,4576,45,car,good